[2024-06-20T23:09:30.456+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T23:09:30.472+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_etl_v51.data_etl.preprocessing_data.convert_to_matrix scheduled__2024-06-20T00:00:00+00:00 [queued]>
[2024-06-20T23:09:30.476+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_etl_v51.data_etl.preprocessing_data.convert_to_matrix scheduled__2024-06-20T00:00:00+00:00 [queued]>
[2024-06-20T23:09:30.477+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-20T23:09:30.485+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_etl.preprocessing_data.convert_to_matrix> on 2024-06-20 00:00:00+00:00
[2024-06-20T23:09:30.490+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3233) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T23:09:30.490+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_data_etl_v51', 'data_etl.preprocessing_data.convert_to_matrix', 'scheduled__2024-06-20T00:00:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/data_etl_dag.py', '--cfg-path', '/tmp/tmp0fp3014o']
[2024-06-20T23:09:30.491+0000] {standard_task_runner.py:63} INFO - Started process 3235 to run task
[2024-06-20T23:09:30.492+0000] {standard_task_runner.py:91} INFO - Job 236: Subtask data_etl.preprocessing_data.convert_to_matrix
[2024-06-20T23:09:30.523+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_data_etl_v51.data_etl.preprocessing_data.convert_to_matrix scheduled__2024-06-20T00:00:00+00:00 [running]> on host 10482076056f
[2024-06-20T23:09:30.567+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Solarev Ruslan' AIRFLOW_CTX_DAG_ID='dag_data_etl_v51' AIRFLOW_CTX_TASK_ID='data_etl.preprocessing_data.convert_to_matrix' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-20T00:00:00+00:00'
[2024-06-20T23:09:30.568+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T23:09:30.582+0000] {logging_mixin.py:188} INFO - Index(['Profession', 'Link', 'Tags'], dtype='object')
[2024-06-20T23:09:30.739+0000] {logging_mixin.py:188} INFO - 0/44
[2024-06-20T23:09:30.741+0000] {logging_mixin.py:188} INFO - 1/44
[2024-06-20T23:09:30.742+0000] {logging_mixin.py:188} INFO - 2/44
[2024-06-20T23:09:30.743+0000] {logging_mixin.py:188} INFO - 3/44
[2024-06-20T23:09:30.744+0000] {logging_mixin.py:188} INFO - 4/44
[2024-06-20T23:09:30.745+0000] {logging_mixin.py:188} INFO - 5/44
[2024-06-20T23:09:30.747+0000] {logging_mixin.py:188} INFO - 6/44
[2024-06-20T23:09:30.748+0000] {logging_mixin.py:188} INFO - 7/44
[2024-06-20T23:09:30.749+0000] {logging_mixin.py:188} INFO - 8/44
[2024-06-20T23:09:30.751+0000] {logging_mixin.py:188} INFO - 9/44
[2024-06-20T23:09:30.753+0000] {logging_mixin.py:188} INFO - 10/44
[2024-06-20T23:09:30.755+0000] {logging_mixin.py:188} INFO - 11/44
[2024-06-20T23:09:30.756+0000] {logging_mixin.py:188} INFO - 12/44
[2024-06-20T23:09:30.759+0000] {logging_mixin.py:188} INFO - 13/44
[2024-06-20T23:09:30.760+0000] {logging_mixin.py:188} INFO - 14/44
[2024-06-20T23:09:30.762+0000] {logging_mixin.py:188} INFO - 15/44
[2024-06-20T23:09:30.764+0000] {logging_mixin.py:188} INFO - 16/44
[2024-06-20T23:09:30.766+0000] {logging_mixin.py:188} INFO - 17/44
[2024-06-20T23:09:30.769+0000] {logging_mixin.py:188} INFO - 18/44
[2024-06-20T23:09:30.772+0000] {logging_mixin.py:188} INFO - 19/44
[2024-06-20T23:09:30.775+0000] {logging_mixin.py:188} INFO - 20/44
[2024-06-20T23:09:30.777+0000] {logging_mixin.py:188} INFO - 21/44
[2024-06-20T23:09:30.780+0000] {logging_mixin.py:188} INFO - 22/44
[2024-06-20T23:09:30.782+0000] {logging_mixin.py:188} INFO - 23/44
[2024-06-20T23:09:30.785+0000] {logging_mixin.py:188} INFO - 24/44
[2024-06-20T23:09:30.788+0000] {logging_mixin.py:188} INFO - 25/44
[2024-06-20T23:09:30.791+0000] {logging_mixin.py:188} INFO - 26/44
[2024-06-20T23:09:30.794+0000] {logging_mixin.py:188} INFO - 27/44
[2024-06-20T23:09:30.798+0000] {logging_mixin.py:188} INFO - 28/44
[2024-06-20T23:09:30.801+0000] {logging_mixin.py:188} INFO - 29/44
[2024-06-20T23:09:30.805+0000] {logging_mixin.py:188} INFO - 30/44
[2024-06-20T23:09:30.809+0000] {logging_mixin.py:188} INFO - 31/44
[2024-06-20T23:09:30.812+0000] {logging_mixin.py:188} INFO - 32/44
[2024-06-20T23:09:30.816+0000] {logging_mixin.py:188} INFO - 33/44
[2024-06-20T23:09:30.822+0000] {logging_mixin.py:188} INFO - 34/44
[2024-06-20T23:09:30.826+0000] {logging_mixin.py:188} INFO - 35/44
[2024-06-20T23:09:30.830+0000] {logging_mixin.py:188} INFO - 36/44
[2024-06-20T23:09:30.834+0000] {logging_mixin.py:188} INFO - 37/44
[2024-06-20T23:09:30.838+0000] {logging_mixin.py:188} INFO - 38/44
[2024-06-20T23:09:30.842+0000] {logging_mixin.py:188} INFO - 39/44
[2024-06-20T23:09:30.847+0000] {logging_mixin.py:188} INFO - 40/44
[2024-06-20T23:09:30.851+0000] {logging_mixin.py:188} INFO - 41/44
[2024-06-20T23:09:30.855+0000] {logging_mixin.py:188} INFO - 42/44
[2024-06-20T23:09:30.860+0000] {logging_mixin.py:188} INFO - 43/44
[2024-06-20T23:09:31.085+0000] {logging_mixin.py:188} INFO - Тип: <class 'pandas.core.frame.DataFrame'>
[2024-06-20T23:18:39.646+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-06-20T23:18:39.647+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-20T23:18:39.648+0000] {process_utils.py:132} INFO - Sending 15 to group 3235. PIDs of all processes in the group: [3235]
[2024-06-20T23:18:39.648+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 3235
[2024-06-20T23:18:39.649+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-20T23:18:39.650+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T23:18:39.655+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/data_preprocessing/convert_to_matrix.py", line 40, in convert_to_matrix
    save_matrix(path=skill_matrix_path, data=user_skill_matrix)
  File "/opt/airflow/dags/tasks/data_preprocessing/convert_to_matrix.py", line 14, in save_matrix
    data.to_csv(path, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 266, in save
    self._save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 271, in _save
    self._save_body()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 309, in _save_body
    self._save_chunk(start_i, end_i)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 316, in _save_chunk
    res = df._mgr.to_native_types(**self._number_format)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 438, in to_native_types
    return self.apply("to_native_types", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 354, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-20T23:18:39.676+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_data_etl_v51, task_id=data_etl.preprocessing_data.convert_to_matrix, run_id=scheduled__2024-06-20T00:00:00+00:00, execution_date=20240620T000000, start_date=20240620T230930, end_date=20240620T231839
[2024-06-20T23:18:39.901+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=3235, status='terminated', exitcode=2, started='23:09:29') (3235) terminated with exit code 2
